#!/usr/bin/env bash
python monolithic_converter_test.py
python pose_interpolator_test.py
python masks_test.py
python apply_gt.py
python png_converter_gt.py
python predict.py
python apply_pred.py
python png_converter_pred.py
python mernos_ro.py
python mernos_gt.py
python mernos_pred.py
